### ISSUE TITLE
Syncing Yahoo Calendar

### ISSUE THREAD

**Issue by DavidA94** [gggard/AndroidCaldavSyncAdapater#37]
I FINALLY figured out a URL that works to sync with my Y! calendar, however, every time I tell it to sync, it crashes. If I try to send a report, it crashes the play store as well.

URL being used: https://caldav.yahoo.com/dav/USERNAME/calendar/CALENDAR_NAME

Here are the errors given when syncing:

03-16 07:31:45.420: E/SyncAdapter(7409): Updating calendar exception java.lang.NullPointerException
03-16 07:31:45.420: E/SyncAdapter(7409): java.lang.NullPointerException
03-16 07:31:45.420: E/SyncAdapter(7409):    at org.apache.http.impl.client.DefaultRequestDirector.rewriteRequestURI(DefaultRequestDirector.java:272)
03-16 07:31:45.420: E/SyncAdapter(7409):    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:383)
03-16 07:31:45.420: E/SyncAdapter(7409):    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
03-16 07:31:45.420: E/SyncAdapter(7409):    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:509)
03-16 07:31:45.420: E/SyncAdapter(7409):    at org.gege.caldavsyncadapter.caldav.CaldavFacade.updateCalendarInfos(CaldavFacade.java:626)
03-16 07:31:45.420: E/SyncAdapter(7409):    at org.gege.caldavsyncadapter.caldav.CaldavFacade.getCalendarList_method1(CaldavFacade.java:602)
03-16 07:31:45.420: E/SyncAdapter(7409):    at org.gege.caldavsyncadapter.caldav.CaldavFacade.getCalendarList(CaldavFacade.java:341)
03-16 07:31:45.420: E/SyncAdapter(7409):    at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:122)
03-16 07:31:45.420: E/SyncAdapter(7409):    at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:247)
03-16 07:31:45.428: W/dalvikvm(7409): threadid=16: thread exiting with uncaught exception (group=0x40a6a228)
03-16 07:31:45.488: E/AndroidRuntime(7409): FATAL EXCEPTION: SyncAdapterThread-1
03-16 07:31:45.488: E/AndroidRuntime(7409): java.lang.RuntimeException: java.lang.NullPointerException
03-16 07:31:45.488: E/AndroidRuntime(7409):     at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:147)
03-16 07:31:45.488: E/AndroidRuntime(7409):     at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:247)
03-16 07:31:45.488: E/AndroidRuntime(7409): Caused by: java.lang.NullPointerException
03-16 07:31:45.488: E/AndroidRuntime(7409):     at org.apache.http.impl.client.DefaultRequestDirector.rewriteRequestURI(DefaultRequestDirector.java:272)
03-16 07:31:45.488: E/AndroidRuntime(7409):     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:383)
03-16 07:31:45.488: E/AndroidRuntime(7409):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
03-16 07:31:45.488: E/AndroidRuntime(7409):     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:509)
03-16 07:31:45.488: E/AndroidRuntime(7409):     at org.gege.caldavsyncadapter.caldav.CaldavFacade.updateCalendarInfos(CaldavFacade.java:626)
03-16 07:31:45.488: E/AndroidRuntime(7409):     at org.gege.caldavsyncadapter.caldav.CaldavFacade.getCalendarList_method1(CaldavFacade.java:602)
03-16 07:31:45.488: E/AndroidRuntime(7409):     at org.gege.caldavsyncadapter.caldav.CaldavFacade.getCalendarList(CaldavFacade.java:341)
03-16 07:31:45.488: E/AndroidRuntime(7409):     at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:122)
03-16 07:31:45.488: E/AndroidRuntime(7409):     ... 1 more

**Comment by dlech** [comment]
I have a patch that should fix this crash. See issue #38.

**Comment by DavidA94** [comment]
I edited the file, and reran the program. I'm still getting the exact same errors, so I don't think it has anything to do with that.

Out of curiosity, why don't you have something like a try catch statement in there for issue #38? I don't know anything about android development yet, but that seems like it should be easy?

**Comment by DavidA94** [comment]
As in issue #33 I'm also getting, "Unfortunately, CalDAV Sync Adapter has stopped." I also no longer have an option to report the crash. But I'm guessing that's because it's no longer installed via the play store?

**Comment by gggard** [comment]
Meesa94 : if you edit the code and run it using Android SDK (Eclipse), you should be able to get the log in the android log view to see what happen, could you send it to us (you can export it as text) (be carefull to remove URL and other personal information).

**Comment by DavidA94** [comment]
Here is everything when I try to sync. Just so you know, on the 81st line, it says "03-17 06:52:38.349: D/CaldavFacade(21029): 6HttpResponse status=HTTP" That 6Http means that it's making it to the 6th one of those in the code (There are seven) From what I could gather using logs to figure out where it was stopping, the issue is somewhere with this code: 

if (node.getNodeName().equalsIgnoreCase("href")) { 
     calendar.setURI(new URI(node.getTextContent()));
}

03-17 06:52:33.028: V/SyncAdapter(21029): onPerformSync() on USERNAME with URL https://caldav.calendar.yahoo.com/dav/USERNAME/Calendar/CAL_NAME
03-17 06:52:33.803: D/dalvikvm(21029): GC_CONCURRENT freed 190K, 5% free 6745K/7047K, paused 0ms+0ms
03-17 06:52:34.742: D/CaldavFacade(21029): 3HttpResponse status=HTTP/1.1 207 Multi Status body= <?xml version="1.0" encoding="UTF-8"?><D:multistatus xmlns:D="DAV:">  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME//D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <CS:getctag xmlns:CS="http://calendarserver.org/ns/">4403-3000/CS:getctag        <D:resourcetype>          <D:collection/>          <C:calendar xmlns:C="urn:ietf:params:xml:ns:caldav"/>          <Y:default-calendar xmlns:Y="http://yahoo.com/ns/"/>        /D:resourcetype        <D:getlastmodified>Sat, 16 Mar 2013 00:02:15 -0700 (PDT)/D:getlastmodified        <D:getcontentlength>0/D:getcontentlength        <D:displayname>CAL_NAME/D:displayname        <D:getetag>"4403-4401"/D:getetag        <D:creationdate>2013-03-16T00:02:15-07:00/D:creationdate      /D:prop    /D:propstat  /D:response/D:multistatus
03-17 06:52:34.743: D/dalvikvm(21029): GC_CONCURRENT freed 335K, 6% free 6873K/7303K, paused 0ms+3ms
03-17 06:52:35.648: D/dalvikvm(21029): GC_CONCURRENT freed 428K, 8% free 6970K/7495K, paused 0ms+4ms
03-17 06:52:35.687: D/dalvikvm(21029): GC_FOR_ALLOC freed 360K, 8% free 6956K/7559K, paused 37ms
03-17 06:52:35.747: D/dalvikvm(21029): GC_FOR_ALLOC freed 347K, 8% free 6964K/7559K, paused 37ms
03-17 06:52:35.782: D/dalvikvm(21029): GC_FOR_ALLOC freed 330K, 8% free 6971K/7559K, paused 30ms
03-17 06:52:35.815: D/dalvikvm(21029): GC_FOR_ALLOC freed 315K, 8% free 6973K/7559K, paused 30ms
03-17 06:52:35.849: D/dalvikvm(21029): GC_FOR_ALLOC freed 314K, 8% free 6975K/7559K, paused 30ms
03-17 06:52:35.881: D/dalvikvm(21029): GC_FOR_ALLOC freed 308K, 8% free 6977K/7559K, paused 30ms
03-17 06:52:35.915: D/dalvikvm(21029): GC_FOR_ALLOC freed 312K, 8% free 6978K/7559K, paused 30ms
03-17 06:52:35.947: D/dalvikvm(21029): GC_FOR_ALLOC freed 308K, 8% free 6974K/7559K, paused 30ms
03-17 06:52:35.979: D/dalvikvm(21029): GC_FOR_ALLOC freed 294K, 8% free 6982K/7559K, paused 27ms
03-17 06:52:36.012: D/dalvikvm(21029): GC_FOR_ALLOC freed 281K, 8% free 6977K/7559K, paused 30ms
03-17 06:52:36.065: D/dalvikvm(21029): GC_FOR_ALLOC freed 306K, 8% free 6978K/7559K, paused 36ms
03-17 06:52:36.145: D/dalvikvm(21029): GC_FOR_ALLOC freed 319K, 8% free 6964K/7559K, paused 76ms
03-17 06:52:36.182: D/dalvikvm(21029): GC_FOR_ALLOC freed 280K, 8% free 6987K/7559K, paused 33ms
03-17 06:52:36.213: D/dalvikvm(21029): GC_FOR_ALLOC freed 313K, 8% free 6965K/7559K, paused 30ms
03-17 06:52:36.246: D/dalvikvm(21029): GC_FOR_ALLOC freed 284K, 8% free 6982K/7559K, paused 30ms
03-17 06:52:36.278: D/dalvikvm(21029): GC_FOR_ALLOC freed 267K, 8% free 6991K/7559K, paused 30ms
03-17 06:52:36.312: D/dalvikvm(21029): GC_FOR_ALLOC freed 341K, 9% free 6984K/7623K, paused 30ms
03-17 06:52:36.345: D/dalvikvm(21029): GC_FOR_ALLOC freed 343K, 9% free 6993K/7623K, paused 30ms
03-17 06:52:36.378: D/dalvikvm(21029): GC_FOR_ALLOC freed 362K, 9% free 6968K/7623K, paused 30ms
03-17 06:52:36.411: D/dalvikvm(21029): GC_FOR_ALLOC freed 327K, 9% free 6987K/7623K, paused 30ms
03-17 06:52:36.444: D/dalvikvm(21029): GC_FOR_ALLOC freed 335K, 9% free 6997K/7623K, paused 30ms
03-17 06:52:36.481: D/dalvikvm(21029): GC_FOR_ALLOC freed 324K, 9% free 6988K/7623K, paused 33ms
03-17 06:52:36.515: D/dalvikvm(21029): GC_FOR_ALLOC freed 371K, 9% free 6970K/7623K, paused 30ms
03-17 06:52:36.546: D/dalvikvm(21029): GC_FOR_ALLOC freed 360K, 9% free 6970K/7623K, paused 30ms
03-17 06:52:36.578: D/dalvikvm(21029): GC_FOR_ALLOC freed 368K, 9% free 6971K/7623K, paused 27ms
03-17 06:52:36.611: D/dalvikvm(21029): GC_FOR_ALLOC freed 355K, 9% free 6992K/7623K, paused 30ms
03-17 06:52:36.644: D/dalvikvm(21029): GC_FOR_ALLOC freed 352K, 9% free 7004K/7623K, paused 30ms
03-17 06:52:36.677: D/dalvikvm(21029): GC_FOR_ALLOC freed 348K, 9% free 6994K/7623K, paused 30ms
03-17 06:52:36.711: D/dalvikvm(21029): GC_FOR_ALLOC freed 321K, 9% free 7005K/7623K, paused 30ms
03-17 06:52:36.745: D/dalvikvm(21029): GC_FOR_ALLOC freed 327K, 9% free 7007K/7623K, paused 26ms
03-17 06:52:36.778: D/dalvikvm(21029): GC_FOR_ALLOC freed 308K, 9% free 7007K/7623K, paused 27ms
03-17 06:52:36.812: D/dalvikvm(21029): GC_FOR_ALLOC freed 349K, 9% free 6973K/7623K, paused 30ms
03-17 06:52:36.844: D/dalvikvm(21029): GC_FOR_ALLOC freed 342K, 9% free 6997K/7623K, paused 30ms
03-17 06:52:36.876: D/dalvikvm(21029): GC_FOR_ALLOC freed 324K, 9% free 6998K/7623K, paused 30ms
03-17 06:52:36.910: D/dalvikvm(21029): GC_FOR_ALLOC freed 304K, 9% free 6999K/7623K, paused 27ms
03-17 06:52:36.942: D/dalvikvm(21029): GC_FOR_ALLOC freed 296K, 9% free 7012K/7623K, paused 27ms
03-17 06:52:36.975: D/dalvikvm(21029): GC_FOR_ALLOC freed 287K, 9% free 7013K/7623K, paused 26ms
03-17 06:52:37.021: D/dalvikvm(21029): GC_FOR_ALLOC freed 278K, 9% free 7013K/7623K, paused 40ms
03-17 06:52:37.052: D/dalvikvm(21029): GC_FOR_ALLOC freed 294K, 8% free 7014K/7623K, paused 30ms
03-17 06:52:37.085: D/dalvikvm(21029): GC_FOR_ALLOC freed 258K, 8% free 7015K/7623K, paused 30ms
03-17 06:52:37.117: D/dalvikvm(21029): GC_FOR_ALLOC freed 261K, 8% free 7015K/7623K, paused 30ms
03-17 06:52:37.149: D/dalvikvm(21029): GC_FOR_ALLOC freed 303K, 9% free 7003K/7623K, paused 30ms
03-17 06:52:37.180: D/dalvikvm(21029): GC_FOR_ALLOC freed 293K, 8% free 7017K/7623K, paused 30ms
03-17 06:52:37.213: D/dalvikvm(21029): GC_FOR_ALLOC freed 309K, 9% free 7004K/7623K, paused 30ms
03-17 06:52:37.244: D/dalvikvm(21029): GC_FOR_ALLOC freed 272K, 8% free 7018K/7623K, paused 26ms
03-17 06:52:37.276: D/dalvikvm(21029): GC_FOR_ALLOC freed 316K, 9% free 6977K/7623K, paused 30ms
03-17 06:52:37.308: D/dalvikvm(21029): GC_FOR_ALLOC freed 277K, 9% free 7006K/7623K, paused 27ms
03-17 06:52:37.342: D/dalvikvm(21029): GC_FOR_ALLOC freed 280K, 8% free 7020K/7623K, paused 30ms
03-17 06:52:37.374: D/dalvikvm(21029): GC_FOR_ALLOC freed 282K, 8% free 7021K/7623K, paused 26ms
03-17 06:52:37.408: D/dalvikvm(21029): GC_FOR_ALLOC freed 299K, 9% free 7007K/7623K, paused 30ms
03-17 06:52:37.442: D/dalvikvm(21029): GC_FOR_ALLOC freed 287K, 9% free 7008K/7623K, paused 30ms
03-17 06:52:37.476: D/dalvikvm(21029): GC_FOR_ALLOC freed 291K, 8% free 7023K/7623K, paused 26ms
03-17 06:52:37.508: D/dalvikvm(21029): GC_FOR_ALLOC freed 293K, 8% free 7023K/7623K, paused 27ms
03-17 06:52:37.546: D/dalvikvm(21029): GC_FOR_ALLOC freed 310K, 9% free 7009K/7623K, paused 37ms
03-17 06:52:37.579: D/dalvikvm(21029): GC_FOR_ALLOC freed 298K, 9% free 7010K/7623K, paused 27ms
03-17 06:52:37.611: D/dalvikvm(21029): GC_FOR_ALLOC freed 301K, 8% free 7025K/7623K, paused 30ms
03-17 06:52:37.644: D/dalvikvm(21029): GC_FOR_ALLOC freed 242K, 8% free 7026K/7623K, paused 30ms
03-17 06:52:37.691: D/dalvikvm(21029): GC_FOR_ALLOC freed 274K, 9% free 7011K/7623K, paused 40ms
03-17 06:52:37.741: D/dalvikvm(21029): GC_FOR_ALLOC freed 277K, 8% free 7027K/7623K, paused 30ms
03-17 06:52:37.775: D/dalvikvm(21029): GC_FOR_ALLOC freed 279K, 9% free 7012K/7623K, paused 30ms
03-17 06:52:37.826: D/dalvikvm(21029): GC_FOR_ALLOC freed 281K, 9% free 7013K/7623K, paused 43ms
03-17 06:52:37.888: D/dalvikvm(21029): GC_FOR_ALLOC freed 251K, 9% free 7013K/7623K, paused 50ms
03-17 06:52:37.919: D/dalvikvm(21029): GC_FOR_ALLOC freed 316K, 9% free 6982K/7623K, paused 30ms
03-17 06:52:37.952: D/dalvikvm(21029): GC_FOR_ALLOC freed 255K, 8% free 7014K/7623K, paused 30ms
03-17 06:52:37.983: D/dalvikvm(21029): GC_FOR_ALLOC freed 321K, 9% free 6982K/7623K, paused 30ms
03-17 06:52:38.053: D/dalvikvm(21029): GC_FOR_ALLOC freed 292K, 8% free 7015K/7623K, paused 64ms
03-17 06:52:38.086: D/dalvikvm(21029): GC_FOR_ALLOC freed 261K, 8% free 7015K/7623K, paused 34ms
03-17 06:52:38.118: D/dalvikvm(21029): GC_FOR_ALLOC freed 328K, 9% free 6983K/7623K, paused 30ms
03-17 06:52:38.151: D/dalvikvm(21029): GC_FOR_ALLOC freed 298K, 8% free 7033K/7623K, paused 30ms
03-17 06:52:38.183: D/dalvikvm(21029): GC_FOR_ALLOC freed 300K, 9% free 6983K/7623K, paused 33ms
03-17 06:52:38.216: D/dalvikvm(21029): GC_FOR_ALLOC freed 303K, 8% free 7017K/7623K, paused 30ms
03-17 06:52:38.246: D/dalvikvm(21029): GC_FOR_ALLOC freed 271K, 9% free 6984K/7623K, paused 30ms
03-17 06:52:38.280: D/dalvikvm(21029): GC_FOR_ALLOC freed 221K, 8% free 7035K/7623K, paused 30ms
03-17 06:52:38.311: D/dalvikvm(21029): GC_FOR_ALLOC freed 274K, 9% free 6984K/7623K, paused 27ms
03-17 06:52:38.344: D/dalvikvm(21029): GC_FOR_ALLOC freed 275K, 8% free 7019K/7623K, paused 30ms
03-17 06:52:38.349: D/CaldavFacade(21029): 6HttpResponse status=HTTP/1.1 207 Multi Status body= <?xml version="1.0" encoding="UTF-8"?><D:multistatus xmlns:D="DAV:">  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME//D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <CS:getctag xmlns:CS="http://calendarserver.org/ns/">4403-3000/CS:getctag        <D:resourcetype>          <D:collection/>          <C:calendar xmlns:C="urn:ietf:params:xml:ns:caldav"/>          <Y:default-calendar xmlns:Y="http://yahoo.com/ns/"/>        /D:resourcetype        <D:getlastmodified>Sat, 16 Mar 2013 00:02:15 -0700 (PDT)/D:getlastmodified        <D:getcontentlength>0/D:getcontentlength        <D:displayname>CAL_NAME/D:displayname        <D:getetag>"4403-4401"/D:getetag        <D:creationdate>2013-03-16T00:02:15-07:00/D:creationdate      /D:prop    /D:propstat  /D:response  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME/49576471-8e24-4928-b4e5-b37ade8b1096.ics/D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <D:resourcetype/>        <D:getetag>"2301-2301"/D:getetag      /D:prop    /D:propstat  /D:response  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME/8e52519a-24e2-4861-8189-9190c467d7c8.ics/D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <D:resourcetype/>        <D:getetag>"2000-2000"/D:getetag      /D:prop    /D:propstat  /D:response  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME/2c91c8f2-5583-4797-8fc9-5d327179e70b.ics/D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <D:resourcetype/>        <D:getetag>"1201-1201"/D:getetag      /D:prop    /D:propstat  /D:response  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME/Nv.EuzRWiMCUV6MK33ww.imhV8o0Qd30HrbMag--@calendar.yahoo.com.ics/D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <D:resourcetype/>        <D:getetag>"22-22"/D:getetag      /D:prop    /D:propstat  /D:response  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME/a81cd779-364a-4889-af61-9c00bd2462b4.ics/D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <D:resourcetype/>        <D:getetag>"900-900"/D:getetag      /D:prop    /D:propstat  /D:response  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME/dadd2deb-c128-4247-b53d-b5eb2d5e1450.ics/D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <D:resourcetype/>        <D:getetag>"2201-2201"/D:getetag      /D:prop    /D:propstat  /D:response  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME/03e2cd77-3b42-4c22-8a15-b12295f28a7d.ics/D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <D:resourcetype/>        <D:getetag>"40-40"/D:getetag      /D:prop    /D:propstat  /D:response  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME/3da6c9ca-7862-443c-949e-73465ad2bc2d.ics/D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <D:resourcetype/>        <D:getetag>"2607-2607"/D:getetag      /D:prop    /D:propstat  /D:response  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME/3c97973d-77c6-43e6-bc3f-bacea77ba7ed.ics/D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <D:resourcetype/>        <D:getetag>"207-207"/D:getetag      /D:prop    /D:propstat  /D:response  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME/3MDK7jRWiMBeGuom2dk39ztnKayXhLgOzLhTVA--@calendar.yahoo.com.ics/D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <D:resourcetype/>        <D:getetag>"2-2"/D:getetag      /D:prop    /D:propstat  /D:response  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME/ea22c38c-5e99-4450-9f45-f122f81d58f4.ics/D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <D:resourcetype/>        <D:getetag>"2001-2001"/D:getetag  
03-17 06:52:38.567: D/dalvikvm(21029): GC_CONCURRENT freed 231K, 6% free 7175K/7623K, paused 0ms+4ms
03-17 06:52:38.675: E/SyncAdapter(21029): Updating calendar exception java.lang.NullPointerException
03-17 06:52:38.675: E/SyncAdapter(21029): java.lang.NullPointerException
03-17 06:52:38.675: E/SyncAdapter(21029):   at org.apache.http.impl.client.DefaultRequestDirector.rewriteRequestURI(DefaultRequestDirector.java:272)
03-17 06:52:38.675: E/SyncAdapter(21029):   at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:383)
03-17 06:52:38.675: E/SyncAdapter(21029):   at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
03-17 06:52:38.675: E/SyncAdapter(21029):   at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:509)
03-17 06:52:38.675: E/SyncAdapter(21029):   at org.gege.caldavsyncadapter.caldav.CaldavFacade.updateCalendarInfos(CaldavFacade.java:626)
03-17 06:52:38.675: E/SyncAdapter(21029):   at org.gege.caldavsyncadapter.caldav.CaldavFacade.getCalendarList_method1(CaldavFacade.java:602)
03-17 06:52:38.675: E/SyncAdapter(21029):   at org.gege.caldavsyncadapter.caldav.CaldavFacade.getCalendarList(CaldavFacade.java:340)
03-17 06:52:38.675: E/SyncAdapter(21029):   at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:122)
03-17 06:52:38.675: E/SyncAdapter(21029):   at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:247)
03-17 06:52:38.685: W/dalvikvm(21029): threadid=11: thread exiting with uncaught exception (group=0x40a6a228)
03-17 06:52:38.687: E/AndroidRuntime(21029): FATAL EXCEPTION: SyncAdapterThread-1
03-17 06:52:38.687: E/AndroidRuntime(21029): java.lang.RuntimeException: java.lang.NullPointerException
03-17 06:52:38.687: E/AndroidRuntime(21029):    at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:147)
03-17 06:52:38.687: E/AndroidRuntime(21029):    at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:247)
03-17 06:52:38.687: E/AndroidRuntime(21029): Caused by: java.lang.NullPointerException
03-17 06:52:38.687: E/AndroidRuntime(21029):    at org.apache.http.impl.client.DefaultRequestDirector.rewriteRequestURI(DefaultRequestDirector.java:272)
03-17 06:52:38.687: E/AndroidRuntime(21029):    at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:383)
03-17 06:52:38.687: E/AndroidRuntime(21029):    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
03-17 06:52:38.687: E/AndroidRuntime(21029):    at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:509)
03-17 06:52:38.687: E/AndroidRuntime(21029):    at org.gege.caldavsyncadapter.caldav.CaldavFacade.updateCalendarInfos(CaldavFacade.java:626)
03-17 06:52:38.687: E/AndroidRuntime(21029):    at org.gege.caldavsyncadapter.caldav.CaldavFacade.getCalendarList_method1(CaldavFacade.java:602)
03-17 06:52:38.687: E/AndroidRuntime(21029):    at org.gege.caldavsyncadapter.caldav.CaldavFacade.getCalendarList(CaldavFacade.java:340)
03-17 06:52:38.687: E/AndroidRuntime(21029):    at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:122)
03-17 06:52:38.687: E/AndroidRuntime(21029):    ... 1 more

---

Now, if I change those lines as suggested by the first responder to
if (node.getLocalName().equalsIgnoreCase("href")) { 
     calendar.setURI(new URI(node.getTextContent()));
}

Then I get the same errors:
03-17 06:59:40.240: V/SyncAdapter(21080): onPerformSync() on USERNAME with URL https://caldav.calendar.yahoo.com/dav/USERNAME/Calendar/CAL_NAME
03-17 06:59:41.063: D/dalvikvm(21080): GC_CONCURRENT freed 193K, 5% free 6746K/7047K, paused 0ms+0ms
03-17 06:59:41.949: D/CaldavFacade(21080): 3HttpResponse status=HTTP/1.1 207 Multi Status body= <?xml version="1.0" encoding="UTF-8"?><D:multistatus xmlns:D="DAV:">  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME//D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <CS:getctag xmlns:CS="http://calendarserver.org/ns/">4403-3000/CS:getctag        <D:resourcetype>          <D:collection/>          <C:calendar xmlns:C="urn:ietf:params:xml:ns:caldav"/>          <Y:default-calendar xmlns:Y="http://yahoo.com/ns/"/>        /D:resourcetype        <D:getlastmodified>Sat, 16 Mar 2013 00:02:15 -0700 (PDT)/D:getlastmodified        <D:getcontentlength>0/D:getcontentlength        <D:displayname>CAL_NAME/D:displayname        <D:getetag>"4403-4401"/D:getetag        <D:creationdate>2013-03-16T00:02:15-07:00/D:creationdate      /D:prop    /D:propstat  /D:response/D:multistatus
03-17 06:59:41.982: D/dalvikvm(21080): GC_CONCURRENT freed 330K, 6% free 6877K/7303K, paused 0ms+7ms
03-17 06:59:42.586: D/dalvikvm(21080): GC_FOR_ALLOC freed 438K, 8% free 6961K/7495K, paused 30ms
03-17 06:59:42.657: D/dalvikvm(21080): GC_CONCURRENT freed 343K, 8% free 6967K/7559K, paused 4ms+4ms
03-17 06:59:42.720: D/dalvikvm(21080): GC_FOR_ALLOC freed 333K, 8% free 6964K/7559K, paused 30ms
03-17 06:59:42.753: D/dalvikvm(21080): GC_FOR_ALLOC freed 347K, 8% free 6958K/7559K, paused 30ms
03-17 06:59:42.787: D/dalvikvm(21080): GC_FOR_ALLOC freed 323K, 8% free 6973K/7559K, paused 34ms
03-17 06:59:42.820: D/dalvikvm(21080): GC_FOR_ALLOC freed 304K, 8% free 6975K/7559K, paused 33ms
03-17 06:59:42.854: D/dalvikvm(21080): GC_FOR_ALLOC freed 307K, 8% free 6972K/7559K, paused 33ms
03-17 06:59:42.884: D/dalvikvm(21080): GC_FOR_ALLOC freed 311K, 8% free 6962K/7559K, paused 30ms
03-17 06:59:42.919: D/dalvikvm(21080): GC_FOR_ALLOC freed 289K, 8% free 6980K/7559K, paused 27ms
03-17 06:59:42.956: D/dalvikvm(21080): GC_FOR_ALLOC freed 267K, 8% free 6982K/7559K, paused 34ms
03-17 06:59:42.988: D/dalvikvm(21080): GC_FOR_ALLOC freed 278K, 8% free 6963K/7559K, paused 30ms
03-17 06:59:43.022: D/dalvikvm(21080): GC_FOR_ALLOC freed 304K, 8% free 6964K/7559K, paused 30ms
03-17 06:59:43.055: D/dalvikvm(21080): GC_FOR_ALLOC freed 302K, 8% free 6964K/7559K, paused 30ms
03-17 06:59:43.089: D/dalvikvm(21080): GC_FOR_ALLOC freed 262K, 8% free 6980K/7559K, paused 30ms
03-17 06:59:43.121: D/dalvikvm(21080): GC_FOR_ALLOC freed 271K, 8% free 6981K/7559K, paused 30ms
03-17 06:59:43.154: D/dalvikvm(21080): GC_FOR_ALLOC freed 256K, 8% free 6989K/7559K, paused 30ms
03-17 06:59:43.186: D/dalvikvm(21080): GC_FOR_ALLOC freed 343K, 9% free 6991K/7623K, paused 30ms
03-17 06:59:43.218: D/dalvikvm(21080): GC_FOR_ALLOC freed 313K, 9% free 6992K/7623K, paused 30ms
03-17 06:59:43.251: D/dalvikvm(21080): GC_FOR_ALLOC freed 331K, 9% free 6967K/7623K, paused 30ms
03-17 06:59:43.284: D/dalvikvm(21080): GC_FOR_ALLOC freed 314K, 9% free 6985K/7623K, paused 30ms
03-17 06:59:43.315: D/dalvikvm(21080): GC_FOR_ALLOC freed 323K, 9% free 6986K/7623K, paused 26ms
03-17 06:59:43.349: D/dalvikvm(21080): GC_FOR_ALLOC freed 303K, 9% free 6997K/7623K, paused 27ms
03-17 06:59:43.382: D/dalvikvm(21080): GC_FOR_ALLOC freed 319K, 9% free 6998K/7623K, paused 27ms
03-17 06:59:43.415: D/dalvikvm(21080): GC_FOR_ALLOC freed 307K, 9% free 6989K/7623K, paused 26ms
03-17 06:59:43.451: D/dalvikvm(21080): GC_FOR_ALLOC freed 324K, 9% free 7000K/7623K, paused 30ms
03-17 06:59:43.482: D/dalvikvm(21080): GC_FOR_ALLOC freed 320K, 9% free 6991K/7623K, paused 27ms
03-17 06:59:43.515: D/dalvikvm(21080): GC_FOR_ALLOC freed 347K, 9% free 6971K/7623K, paused 26ms
03-17 06:59:43.549: D/dalvikvm(21080): GC_FOR_ALLOC freed 302K, 9% free 7003K/7623K, paused 30ms
03-17 06:59:43.582: D/dalvikvm(21080): GC_FOR_ALLOC freed 286K, 9% free 6993K/7623K, paused 27ms
03-17 06:59:43.615: D/dalvikvm(21080): GC_FOR_ALLOC freed 313K, 9% free 7004K/7623K, paused 26ms
03-17 06:59:43.649: D/dalvikvm(21080): GC_FOR_ALLOC freed 296K, 9% free 7005K/7623K, paused 27ms
03-17 06:59:43.685: D/dalvikvm(21080): GC_FOR_ALLOC freed 278K, 9% free 6995K/7623K, paused 30ms
03-17 06:59:43.717: D/dalvikvm(21080): GC_FOR_ALLOC freed 305K, 9% free 7007K/7623K, paused 30ms
03-17 06:59:43.750: D/dalvikvm(21080): GC_FOR_ALLOC freed 309K, 9% free 6973K/7623K, paused 30ms
03-17 06:59:43.784: D/dalvikvm(21080): GC_FOR_ALLOC freed 291K, 9% free 6997K/7623K, paused 30ms
03-17 06:59:43.818: D/dalvikvm(21080): GC_FOR_ALLOC freed 342K, 9% free 6974K/7623K, paused 30ms
03-17 06:59:43.851: D/dalvikvm(21080): GC_FOR_ALLOC freed 324K, 9% free 6998K/7623K, paused 30ms
03-17 06:59:43.884: D/dalvikvm(21080): GC_FOR_ALLOC freed 304K, 9% free 6999K/7623K, paused 27ms
03-17 06:59:43.918: D/dalvikvm(21080): GC_FOR_ALLOC freed 296K, 9% free 7012K/7623K, paused 27ms
03-17 06:59:43.953: D/dalvikvm(21080): GC_FOR_ALLOC freed 287K, 9% free 7013K/7623K, paused 33ms
03-17 06:59:43.987: D/dalvikvm(21080): GC_FOR_ALLOC freed 278K, 9% free 7013K/7623K, paused 30ms
03-17 06:59:44.027: D/dalvikvm(21080): GC_FOR_ALLOC freed 294K, 8% free 7014K/7623K, paused 37ms
03-17 06:59:44.060: D/dalvikvm(21080): GC_FOR_ALLOC freed 258K, 8% free 7015K/7623K, paused 33ms
03-17 06:59:44.091: D/dalvikvm(21080): GC_FOR_ALLOC freed 261K, 8% free 7016K/7623K, paused 30ms
03-17 06:59:44.123: D/dalvikvm(21080): GC_FOR_ALLOC freed 303K, 9% free 7003K/7623K, paused 30ms
03-17 06:59:44.154: D/dalvikvm(21080): GC_FOR_ALLOC freed 293K, 8% free 7017K/7623K, paused 30ms
03-17 06:59:44.186: D/dalvikvm(21080): GC_FOR_ALLOC freed 309K, 9% free 7004K/7623K, paused 30ms
03-17 06:59:44.217: D/dalvikvm(21080): GC_FOR_ALLOC freed 272K, 8% free 7018K/7623K, paused 30ms
03-17 06:59:44.249: D/dalvikvm(21080): GC_FOR_ALLOC freed 316K, 9% free 6978K/7623K, paused 27ms
03-17 06:59:44.284: D/dalvikvm(21080): GC_FOR_ALLOC freed 277K, 9% free 7006K/7623K, paused 30ms
03-17 06:59:44.323: D/dalvikvm(21080): GC_FOR_ALLOC freed 280K, 8% free 7020K/7623K, paused 36ms
03-17 06:59:44.354: D/dalvikvm(21080): GC_FOR_ALLOC freed 282K, 8% free 7021K/7623K, paused 30ms
03-17 06:59:44.387: D/dalvikvm(21080): GC_FOR_ALLOC freed 299K, 9% free 7007K/7623K, paused 30ms
03-17 06:59:44.419: D/dalvikvm(21080): GC_FOR_ALLOC freed 287K, 9% free 7008K/7623K, paused 30ms
03-17 06:59:44.453: D/dalvikvm(21080): GC_FOR_ALLOC freed 291K, 8% free 7023K/7623K, paused 30ms
03-17 06:59:44.485: D/dalvikvm(21080): GC_FOR_ALLOC freed 293K, 8% free 7024K/7623K, paused 26ms
03-17 06:59:44.515: D/dalvikvm(21080): GC_FOR_ALLOC freed 310K, 9% free 7009K/7623K, paused 26ms
03-17 06:59:44.548: D/dalvikvm(21080): GC_FOR_ALLOC freed 298K, 9% free 7010K/7623K, paused 27ms
03-17 06:59:44.583: D/dalvikvm(21080): GC_FOR_ALLOC freed 301K, 8% free 7026K/7623K, paused 33ms
03-17 06:59:44.615: D/dalvikvm(21080): GC_FOR_ALLOC freed 242K, 8% free 7026K/7623K, paused 26ms
03-17 06:59:44.648: D/dalvikvm(21080): GC_FOR_ALLOC freed 274K, 9% free 7011K/7623K, paused 27ms
03-17 06:59:44.681: D/dalvikvm(21080): GC_FOR_ALLOC freed 277K, 8% free 7027K/7623K, paused 30ms
03-17 06:59:44.715: D/dalvikvm(21080): GC_FOR_ALLOC freed 279K, 9% free 7012K/7623K, paused 26ms
03-17 06:59:44.749: D/dalvikvm(21080): GC_FOR_ALLOC freed 281K, 9% free 7013K/7623K, paused 27ms
03-17 06:59:44.782: D/dalvikvm(21080): GC_FOR_ALLOC freed 251K, 9% free 7013K/7623K, paused 30ms
03-17 06:59:44.815: D/dalvikvm(21080): GC_FOR_ALLOC freed 316K, 9% free 6982K/7623K, paused 26ms
03-17 06:59:44.849: D/dalvikvm(21080): GC_FOR_ALLOC freed 255K, 8% free 7014K/7623K, paused 30ms
03-17 06:59:44.885: D/dalvikvm(21080): GC_FOR_ALLOC freed 321K, 9% free 6982K/7623K, paused 30ms
03-17 06:59:44.918: D/dalvikvm(21080): GC_FOR_ALLOC freed 292K, 8% free 7015K/7623K, paused 30ms
03-17 06:59:44.953: D/dalvikvm(21080): GC_FOR_ALLOC freed 261K, 8% free 7016K/7623K, paused 33ms
03-17 06:59:44.985: D/dalvikvm(21080): GC_FOR_ALLOC freed 246K, 8% free 7032K/7623K, paused 30ms
03-17 06:59:45.017: D/dalvikvm(21080): GC_FOR_ALLOC freed 264K, 8% free 7033K/7623K, paused 26ms
03-17 06:59:45.047: D/dalvikvm(21080): GC_FOR_ALLOC freed 233K, 8% free 7017K/7623K, paused 27ms
03-17 06:59:45.081: D/dalvikvm(21080): GC_FOR_ALLOC freed 251K, 8% free 7034K/7623K, paused 30ms
03-17 06:59:45.113: D/dalvikvm(21080): GC_FOR_ALLOC freed 235K, 8% free 7018K/7623K, paused 30ms
03-17 06:59:45.146: D/dalvikvm(21080): GC_FOR_ALLOC freed 271K, 9% free 6984K/7623K, paused 34ms
03-17 06:59:45.179: D/dalvikvm(21080): GC_FOR_ALLOC freed 221K, 8% free 7035K/7623K, paused 33ms
03-17 06:59:45.213: D/dalvikvm(21080): GC_FOR_ALLOC freed 188K, 8% free 7036K/7623K, paused 33ms
03-17 06:59:45.245: D/dalvikvm(21080): GC_FOR_ALLOC freed 206K, 8% free 7019K/7623K, paused 30ms
03-17 06:59:45.278: D/dalvikvm(21080): GC_FOR_ALLOC freed 224K, 8% free 7036K/7623K, paused 30ms
03-17 06:59:45.281: D/CaldavFacade(21080): 6HttpResponse status=HTTP/1.1 207 Multi Status body= <?xml version="1.0" encoding="UTF-8"?><D:multistatus xmlns:D="DAV:">  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME//D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <CS:getctag xmlns:CS="http://calendarserver.org/ns/">4403-3000/CS:getctag        <D:resourcetype>          <D:collection/>          <C:calendar xmlns:C="urn:ietf:params:xml:ns:caldav"/>          <Y:default-calendar xmlns:Y="http://yahoo.com/ns/"/>        /D:resourcetype        <D:getlastmodified>Sat, 16 Mar 2013 00:02:15 -0700 (PDT)/D:getlastmodified        <D:getcontentlength>0/D:getcontentlength        <D:displayname>CAL_NAME/D:displayname        <D:getetag>"4403-4401"/D:getetag        <D:creationdate>2013-03-16T00:02:15-07:00/D:creationdate      /D:prop    /D:propstat  /D:response  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME/49576471-8e24-4928-b4e5-b37ade8b1096.ics/D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <D:resourcetype/>        <D:getetag>"2301-2301"/D:getetag      /D:prop    /D:propstat  /D:response  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME/8e52519a-24e2-4861-8189-9190c467d7c8.ics/D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <D:resourcetype/>        <D:getetag>"2000-2000"/D:getetag      /D:prop    /D:propstat  /D:response  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME/2c91c8f2-5583-4797-8fc9-5d327179e70b.ics/D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <D:resourcetype/>        <D:getetag>"1201-1201"/D:getetag      /D:prop    /D:propstat  /D:response  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME/Nv.EuzRWiMCUV6MK33ww.imhV8o0Qd30HrbMag--@calendar.yahoo.com.ics/D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <D:resourcetype/>        <D:getetag>"22-22"/D:getetag      /D:prop    /D:propstat  /D:response  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME/a81cd779-364a-4889-af61-9c00bd2462b4.ics/D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <D:resourcetype/>        <D:getetag>"900-900"/D:getetag      /D:prop    /D:propstat  /D:response  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME/dadd2deb-c128-4247-b53d-b5eb2d5e1450.ics/D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <D:resourcetype/>        <D:getetag>"2201-2201"/D:getetag      /D:prop    /D:propstat  /D:response  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME/03e2cd77-3b42-4c22-8a15-b12295f28a7d.ics/D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <D:resourcetype/>        <D:getetag>"40-40"/D:getetag      /D:prop    /D:propstat  /D:response  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME/3da6c9ca-7862-443c-949e-73465ad2bc2d.ics/D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <D:resourcetype/>        <D:getetag>"2607-2607"/D:getetag      /D:prop    /D:propstat  /D:response  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME/3c97973d-77c6-43e6-bc3f-bacea77ba7ed.ics/D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <D:resourcetype/>        <D:getetag>"207-207"/D:getetag      /D:prop    /D:propstat  /D:response  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME/3MDK7jRWiMBeGuom2dk39ztnKayXhLgOzLhTVA--@calendar.yahoo.com.ics/D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <D:resourcetype/>        <D:getetag>"2-2"/D:getetag      /D:prop    /D:propstat  /D:response  <D:response>    <D:href>/dav/USERNAME/Calendar/CAL_NAME/ea22c38c-5e99-4450-9f45-f122f81d58f4.ics/D:href    <D:propstat>      <D:status>HTTP/1.1 200 OK/D:status      <D:prop>        <D:resourcetype/>        <D:getetag>"2001-2001"/D:getetag  
03-17 06:59:46.015: E/SyncAdapter(21080): Updating calendar exception java.lang.NullPointerException
03-17 06:59:46.015: E/SyncAdapter(21080): java.lang.NullPointerException
03-17 06:59:46.015: E/SyncAdapter(21080):   at org.gege.caldavsyncadapter.caldav.CaldavFacade.getCalendarList_method1(CaldavFacade.java:597)
03-17 06:59:46.015: E/SyncAdapter(21080):   at org.gege.caldavsyncadapter.caldav.CaldavFacade.getCalendarList(CaldavFacade.java:340)
03-17 06:59:46.015: E/SyncAdapter(21080):   at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:122)
03-17 06:59:46.015: E/SyncAdapter(21080):   at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:247)
03-17 06:59:46.061: D/dalvikvm(21080): GC_CONCURRENT freed 551K, 10% free 6873K/7623K, paused 0ms+3ms
03-17 06:59:46.079: W/dalvikvm(21080): threadid=11: thread exiting with uncaught exception (group=0x40a6a228)
03-17 06:59:46.092: E/AndroidRuntime(21080): FATAL EXCEPTION: SyncAdapterThread-1
03-17 06:59:46.092: E/AndroidRuntime(21080): java.lang.RuntimeException: java.lang.NullPointerException
03-17 06:59:46.092: E/AndroidRuntime(21080):    at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:147)
03-17 06:59:46.092: E/AndroidRuntime(21080):    at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:247)
03-17 06:59:46.092: E/AndroidRuntime(21080): Caused by: java.lang.NullPointerException
03-17 06:59:46.092: E/AndroidRuntime(21080):    at org.gege.caldavsyncadapter.caldav.CaldavFacade.getCalendarList_method1(CaldavFacade.java:597)
03-17 06:59:46.092: E/AndroidRuntime(21080):    at org.gege.caldavsyncadapter.caldav.CaldavFacade.getCalendarList(CaldavFacade.java:340)
03-17 06:59:46.092: E/AndroidRuntime(21080):    at org.gege.caldavsyncadapter.syncadapter.SyncAdapter.onPerformSync(SyncAdapter.java:122)
03-17 06:59:46.092: E/AndroidRuntime(21080):    ... 1 more
03-17 06:59:52.340: I/Process(21080): Sending signal. PID: 21080 SIG: 9

**Comment by DavidA94** [comment]
Any findings on this?

**Comment by DavidA94** [comment]
Crash issue solved with Update 1.7.
